import type { Metadata } from "next";
import TokenGuard from "@/components/tokenGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <TokenGuard>{children}</TokenGuard>;
}
