import Link from "next/link";
import Image from "next/image";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Daftar | Tokped",
  description: "Generated by create next app",
};
import { redirect } from "next/navigation";
import ErrorDialog from "@/components/errorDialog";
import { Response, UserOutput } from "@/db/types";
import { baseUrl } from "@/db/c";
export default async function Page() {
  const postUser = async (formData: FormData) => {
    "use server";

    // pke model
    const response = await fetch(`${baseUrl}/api/users`, {
      method: "POST",
      body: JSON.stringify({
        username: formData.get("username"),
        email: formData.get("email"),
        password: formData.get("password"),
      }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    const responseJson: Response<UserOutput> = await response.json();

    if (!response.ok) {
      let message = responseJson.error ?? "Something went wrong!";
      return redirect(`/register?error=${message}`);
    }

    return redirect("/login");
  };
  return (
    <>
      <header className="register-header">
        <Link href={"/"}>
          <Image
            className="register-header-logo"
            src="/logo.svg"
            width={160}
            height={34}
            alt="Picture of the author"
          />
        </Link>
      </header>
      <main>
        <section>
          <div className="container">
            <div className="register-img-form-con">
              <div className="register-left-con">
                <Image
                  src="/register-img.png"
                  width={360}
                  height={303}
                  alt="Picture of the author"
                />
                <h2 className="register-left-title">
                  Jual Beli Mudah Hanya di Tokopedia
                </h2>
                <p className="register-left-p">
                  Gabung dan rasakan kemudahan bertransaksi di Tokopedia
                </p>
              </div>
              <div className="register-form-con">
                <h1>Daftar Sekarang</h1>
                <p className="register-form-p">
                  Sudah punya akun Tokopedia?{" "}
                  <Link className="title-green-link" href={"/login"}>
                    Masuk
                  </Link>
                </p>
                <form className="register-form" action={postUser}>
                  <label className="register-form-label mt0" htmlFor="username">
                    Username
                  </label>
                  <input
                    className="register-form-text-input"
                    type="text"
                    id="username"
                    name="username"
                    placeholder="Username"
                  />
                  <p className="register-form-p">Example: william</p>
                  <label className="register-form-label" htmlFor="email">
                    Email
                  </label>
                  <input
                    className="register-form-text-input"
                    type="text"
                    id="email"
                    name="email"
                    placeholder="Email"
                  />
                  <p className="register-form-p">
                    Example: email@tokopedia.com
                  </p>
                  <label className="register-form-label" htmlFor="password">
                    Password
                  </label>
                  <input
                    className="register-form-text-input"
                    type="password"
                    id="password"
                    name="password"
                    placeholder="Password"
                  />
                  <p className="register-form-p">Password: 123456</p>
                  <button type="submit" className="register-form-button">
                    Daftar
                  </button>
                </form>
                <p className="register-form-policy">
                  Dengan mendaftar, saya menyetujui <br /> Syarat dan Ketentuan
                  serta Kebijakan Privasi
                </p>
              </div>
            </div>
          </div>
          <footer className="register-footer">
            <p>
              © 2009-2024, PT Tokopedia{" "}
              <Link className="title-green-link" href={"/"}>
                Tokopedia Care
              </Link>
            </p>
          </footer>
        </section>
      </main>
    </>
  );
}
