import Link from "next/link";
import Image from "next/image";
import { Metadata } from "next";
import { ZodUserInput } from "@/db/types";
import { redirect } from "next/navigation";
import { getUserByEmail } from "@/db/models/user";
import { compare, sign } from "@/db/helper";
import { cookies } from "next/headers";
import { baseUrl } from "@/db/c";
export const metadata: Metadata = {
  title: "Masuk | Tokped",
  description: "Generated by create next app",
};
export default async function Page() {
  const login = async (formData: FormData) => {
    "use server";
    // get form
    const username = formData.get("username");
    const email = formData.get("email");
    const password = formData.get("password");
    // zod check
    const parsedData = ZodUserInput.safeParse({
      username,
      email,
      password,
    });
    // invalid input?
    if (!parsedData.success) {
      const errPath = parsedData.error.issues[0].path[0];
      const errMessage = parsedData.error.issues[0].message;
      const errFinalMessage = `${errPath} - ${errMessage}`;
      // go back here with error query
      return redirect(`${baseUrl}/login?error=${errFinalMessage}`);
    }
    // no user? wrong password?
    const user = await getUserByEmail(parsedData.data.email);
    if (!user || !compare(parsedData.data.password, user.password)) {
      // go back here with error query
      return redirect(`${baseUrl}/login?error=Invalid%20credentials`);
    }
    // payload -> token
    const payload = {
      id: user._id,
    };
    const token = sign(payload);
    // save token to cookie
    cookies().set("token", token, {
      httpOnly: true,
      secure: false,
      // expires: new Date(Date.now() + 1000 * 60 * 60), // 1 hour
      sameSite: "strict",
    });
    // kick ke dashboard
    return redirect(`/product`);
  };
  return (
    <>
      <header className="register-header">
        <Link href={"/"}>
          <Image
            className="register-header-logo"
            src="/logo.svg"
            width={160}
            height={34}
            alt="Picture of the author"
          />
        </Link>
      </header>
      <main>
        <section>
          <div className="container">
            <div className="register-img-form-con">
              <div className="register-left-con">
                <Image
                  src="/register-img.png"
                  width={360}
                  height={303}
                  alt="Picture of the author"
                />
                <h2 className="register-left-title">
                  Jual Beli Mudah Hanya di Tokopedia
                </h2>
                <p className="register-left-p">
                  Gabung dan rasakan kemudahan bertransaksi di Tokopedia
                </p>
              </div>
              <div className="register-form-con">
                <h1>Masuk Sekarang</h1>
                <p className="register-form-p">
                  Tidak punya akun Tokopedia?{" "}
                  <Link className="title-green-link" href={"/register"}>
                    Daftar
                  </Link>
                </p>
                <form className="register-form" action={login}>
                  <label className="register-form-label mt0" htmlFor="username">
                    Username
                  </label>
                  <input
                    className="register-form-text-input"
                    type="text"
                    id="username"
                    name="username"
                    placeholder="Username"
                  />
                  <p className="register-form-p">Example: william</p>
                  <label className="register-form-label" htmlFor="email">
                    Email
                  </label>
                  <input
                    className="register-form-text-input"
                    type="text"
                    id="email"
                    name="email"
                    placeholder="Email"
                  />
                  <p className="register-form-p">
                    Example: email@tokopedia.com
                  </p>
                  <label className="register-form-label" htmlFor="password">
                    Password
                  </label>
                  <input
                    className="register-form-text-input"
                    type="password"
                    id="password"
                    name="password"
                    placeholder="Password"
                  />
                  <p className="register-form-p">Password: 123456</p>
                  <button className="register-form-button">Daftar</button>
                </form>
                <p className="register-form-policy">
                  Dengan masuk, saya menyetujui <br /> Syarat dan Ketentuan
                  serta Kebijakan Privasi
                </p>
              </div>
            </div>
          </div>
          <footer className="register-footer">
            <p>
              © 2009-2024, PT Tokopedia{" "}
              <Link className="title-green-link" href={"/"}>
                Tokopedia Care
              </Link>
            </p>
          </footer>
        </section>
      </main>
    </>
  );
}
